parameters:
#    deliverme_menu.example.class: Deliverme\MenuBundle\Example

services:
#    deliverme_menu.example:
#        class: %deliverme_menu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
