client:
    path:     /
    defaults: { _controller: "DelivermeMenuBundle:Client:index" }

client_show:
    path:     /{id}/show
    defaults: { _controller: "DelivermeMenuBundle:Client:show" }

client_new:
    path:     /new
    defaults: { _controller: "DelivermeMenuBundle:Client:new" }

client_create:
    path:     /create
    defaults: { _controller: "DelivermeMenuBundle:Client:create" }
    methods:  POST

client_edit:
    path:     /{id}/edit
    defaults: { _controller: "DelivermeMenuBundle:Client:edit" }

client_update:
    path:     /{id}/update
    defaults: { _controller: "DelivermeMenuBundle:Client:update" }
    methods:  [POST, PUT]

client_delete:
    path:     /{id}/delete
    defaults: { _controller: "DelivermeMenuBundle:Client:delete" }
    methods:  [POST, DELETE]
