<?php

namespace Deliverme\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeliveryManRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryManRepository extends EntityRepository
{
}
