<?php

namespace Deliverme\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DishesTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishesTypeRepository extends EntityRepository
{
    
}
