<?php

namespace Proxies\__CG__\Deliverme\MenuBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CartShopping extends \Deliverme\MenuBundle\Entity\CartShopping implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'id', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'reference', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'totalPrice', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'deliveryPrice', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'status', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'data_created', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'data_updated', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'client', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'clientAdress', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'deliveryMan'];
        }

        return ['__isInitialized__', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'id', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'reference', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'totalPrice', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'deliveryPrice', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'status', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'data_created', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'data_updated', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'client', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'clientAdress', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\CartShopping' . "\0" . 'deliveryMan'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CartShopping $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalPrice($totalPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalPrice', [$totalPrice]);

        return parent::setTotalPrice($totalPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalPrice', []);

        return parent::getTotalPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryPrice($deliveryPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryPrice', [$deliveryPrice]);

        return parent::setDeliveryPrice($deliveryPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryPrice', []);

        return parent::getDeliveryPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCreated($dataCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCreated', [$dataCreated]);

        return parent::setDataCreated($dataCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCreated', []);

        return parent::getDataCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataUpdated($dataUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataUpdated', [$dataUpdated]);

        return parent::setDataUpdated($dataUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataUpdated', []);

        return parent::getDataUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function updateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateDate', []);

        return parent::updateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function createDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createDate', []);

        return parent::createDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient(\Deliverme\MenuBundle\Entity\Client $client = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', [$client]);

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', []);

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientAdress(\Deliverme\MenuBundle\Entity\ClientAdress $clientAdress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientAdress', [$clientAdress]);

        return parent::setClientAdress($clientAdress);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAdress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAdress', []);

        return parent::getClientAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryMan(\Deliverme\MenuBundle\Entity\DeliveryMan $deliveryMan = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryMan', [$deliveryMan]);

        return parent::setDeliveryMan($deliveryMan);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryMan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryMan', []);

        return parent::getDeliveryMan();
    }

}
