<?php

namespace Proxies\__CG__\Deliverme\MenuBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Dishes extends \Deliverme\MenuBundle\Entity\Dishes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'id', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'name', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'ingredients', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'price', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'status', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'ranking', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'data_created', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'data_updated', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'dishesType', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'photo', 'file', 'tmp'];
        }

        return ['__isInitialized__', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'id', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'name', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'ingredients', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'price', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'status', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'ranking', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'data_created', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'data_updated', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'dishesType', '' . "\0" . 'Deliverme\\MenuBundle\\Entity\\Dishes' . "\0" . 'photo', 'file', 'tmp'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Dishes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIngredients($ingredients)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIngredients', [$ingredients]);

        return parent::setIngredients($ingredients);
    }

    /**
     * {@inheritDoc}
     */
    public function getIngredients()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIngredients', []);

        return parent::getIngredients();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setRanking($ranking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRanking', [$ranking]);

        return parent::setRanking($ranking);
    }

    /**
     * {@inheritDoc}
     */
    public function getRanking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRanking', []);

        return parent::getRanking();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataCreated($dataCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataCreated', [$dataCreated]);

        return parent::setDataCreated($dataCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataCreated', []);

        return parent::getDataCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataUpdated($dataUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataUpdated', [$dataUpdated]);

        return parent::setDataUpdated($dataUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataUpdated', []);

        return parent::getDataUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDishesType(\Deliverme\MenuBundle\Entity\DishesType $dishesType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDishesType', [$dishesType]);

        return parent::setDishesType($dishesType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDishesType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDishesType', []);

        return parent::getDishesType();
    }

    /**
     * {@inheritDoc}
     */
    public function updateDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateDate', []);

        return parent::updateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function createDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'createDate', []);

        return parent::createDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsulatePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsulatePath', []);

        return parent::getAbsulatePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', []);

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', []);

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', []);

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function storeFilenameForRemove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'storeFilenameForRemove', []);

        return parent::storeFilenameForRemove();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', []);

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getTmp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTmp', []);

        return parent::getTmp();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function setTmp($tmp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTmp', [$tmp]);

        return parent::setTmp($tmp);
    }

}
